language: objective-c

#before_install:
#- rvm --default use 2.0.0
#- ruby -v
#- brew --version
#- xctool -version
#- xcodebuild -version -sdk

script: xctool -project Ethylocle.xcodeproj -scheme Ethylocle -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test


#language: objective-c
#xcode_project: Ethlocle.xcodeproj # path to your xcodeproj folder
#xcode_scheme: Ethylocle
